site_name: CombinedDynamic
site_url: https://xmariohux.github.io/CombinedDynamic-Doc.io/docs/

theme:
  logo: assets/logo.png
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - tags
  - i18n:
      languages:
        - locale: en
          name: English

        - locale: zh
          default: true
          name: 中文
          nav_translations:
            Home: 主页
            Update Logs: 更新日志
            Documention: 接口文档
            Built In Tags: 内置tag
            Tag Components: tag组件
            Built In Interfaces: 内置接口类型
            Script Events: 脚本事件
            Enums: 枚举值

nav:
  - Home: index.md
  - Update Logs:
    - logs/index.md
    - Alpha 0.6.0: logs/alpha060.md
  - Documention:
    - docs/index.md
    - Built In Tags:
      - combined_dynamic:is_wrench: docs/built_in_tags/is_wrench.md
    - Tag Components:
      - combined_dynamic:fuel: docs/tag_components/fuel.md
      - combined_dynamic:pressable: docs/tag_components/pressable.md
    - Built In Interfaces:
      - ItemIngredient: docs/built_in_interfaces/item_ingredient.md
      - TagIngredient: docs/built_in_interfaces/tag_ingredient.md
      - ItemResult: docs/built_in_interfaces/item_result.md
    - Script Events:
      - combined_dynamic:recipe_register: docs/script_events/recipe_register.md
    - Enums:
      - GasTypes: docs/enums/gas_types.md
      - LiquidTypes: docs/enums/liquid_types.md